package lockfile

// HCL emitter for .forge-lock.hcl.
//
// Mirrors the structure of internal/config/hclemit.go: hclwrite builds
// the canonical HCL output from the in-memory Lockfile struct so the
// loader/emitter pair round-trips cleanly.

import (
	"fmt"
	"io"
	"sort"
	"time"

	"github.com/hashicorp/hcl/v2/hclwrite"
	"github.com/zclconf/go-cty/cty"
)

// HCLHeader is prepended to every .forge-lock.hcl file written by
// WriteLockfileHCL. Matches the YAML header style for parity with the
// existing lockfile writer.
const HCLHeader = "# .forge-lock.hcl — DO NOT EDIT MANUALLY\n" +
	"# Generated by forge. Changes will be overwritten on sync.\n\n"

// WriteLockfileHCL emits lock as .forge-lock.hcl-shaped HCL into w.
// The produced output round-trips through LoadLockfileHCL.
func WriteLockfileHCL(w io.Writer, lock *Lockfile) error {
	if _, err := io.WriteString(w, HCLHeader); err != nil {
		return fmt.Errorf("writing lockfile header: %w", err)
	}

	f := hclwrite.NewEmptyFile()
	body := f.Body()

	writeBlueprintBlock(body, &lock.Blueprint)

	body.AppendNewline()
	body.SetAttributeValue("created_at", cty.StringVal(formatTime(lock.CreatedAt)))
	body.SetAttributeValue("last_synced", cty.StringVal(formatTime(lock.LastSynced)))
	body.SetAttributeValue("forge_version", cty.StringVal(lock.ForgeVersion))

	if len(lock.Variables) > 0 {
		body.AppendNewline()

		if err := writeVariablesBlock(body, lock.Variables); err != nil {
			return err
		}
	}

	for i := range lock.Defaults {
		body.AppendNewline()
		writeDefaultBlock(body, &lock.Defaults[i])
	}

	for i := range lock.ManagedFiles {
		body.AppendNewline()
		writeManagedFileBlock(body, &lock.ManagedFiles[i])
	}

	if _, err := f.WriteTo(w); err != nil {
		return fmt.Errorf("writing lockfile hcl: %w", err)
	}

	return nil
}

func writeBlueprintBlock(body *hclwrite.Body, ref *BlueprintRef) {
	block := body.AppendNewBlock("blueprint", nil).Body()
	block.SetAttributeValue("registry_url", cty.StringVal(ref.RegistryURL))
	block.SetAttributeValue("name", cty.StringVal(ref.Name))
	block.SetAttributeValue("path", cty.StringVal(ref.Path))

	if ref.Ref != "" {
		block.SetAttributeValue("ref", cty.StringVal(ref.Ref))
	}

	if ref.Commit != "" {
		block.SetAttributeValue("commit", cty.StringVal(ref.Commit))
	}
}

func writeVariablesBlock(body *hclwrite.Body, vars map[string]any) error {
	block := body.AppendNewBlock("variables", nil).Body()

	// Sorted output keeps the lockfile diffable across runs even if
	// the map iteration order changes.
	keys := make([]string, 0, len(vars))
	for k := range vars {
		keys = append(keys, k)
	}

	sort.Strings(keys)

	for _, k := range keys {
		val, err := ctyForVariableValue(vars[k])
		if err != nil {
			return fmt.Errorf("variable %q: %w", k, err)
		}

		block.SetAttributeValue(k, val)
	}

	return nil
}

func writeDefaultBlock(body *hclwrite.Body, entry *DefaultEntry) {
	block := body.AppendNewBlock("default", []string{entry.Path}).Body()
	block.SetAttributeValue("source", cty.StringVal(entry.Source))
	block.SetAttributeValue("strategy", cty.StringVal(entry.Strategy))

	if entry.Hash != "" {
		block.SetAttributeValue("hash", cty.StringVal(entry.Hash))
	}

	if entry.SyncedCommit != "" {
		block.SetAttributeValue("synced_commit", cty.StringVal(entry.SyncedCommit))
	}
}

func writeManagedFileBlock(body *hclwrite.Body, entry *ManagedFileEntry) {
	block := body.AppendNewBlock("managed_file", []string{entry.Path}).Body()
	block.SetAttributeValue("strategy", cty.StringVal(entry.Strategy))

	if entry.Hash != "" {
		block.SetAttributeValue("hash", cty.StringVal(entry.Hash))
	}

	if entry.SyncedCommit != "" {
		block.SetAttributeValue("synced_commit", cty.StringVal(entry.SyncedCommit))
	}
}

// ctyForVariableValue converts a raw lockfile variable value to a
// cty.Value suitable for hclwrite. The Lockfile struct carries
// map[string]any without declared-type information, so this helper
// infers the cty type from the Go type at emit time. Mirrors the
// inferValue helper in cty.go but exposes a single entry point for the
// emitter.
func ctyForVariableValue(v any) (cty.Value, error) {
	if v == nil {
		return cty.NullVal(cty.String), nil
	}

	return inferValue(v)
}

// formatTime returns the RFC3339-with-nanos representation of t, or
// the empty string for a zero-valued time. Empty strings round-trip
// to zero-valued time.Time in the loader.
func formatTime(t time.Time) string {
	if t.IsZero() {
		return ""
	}

	return t.Format(time.RFC3339Nano)
}
