// Package lockfile manages .forge-lock.{hcl,yaml} state tracking for
// scaffolded projects. HCL is the canonical on-disk format from v0.5+;
// YAML continues to load during the IMPL-0006 transition phase.
package lockfile

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"gopkg.in/yaml.v3"
)

const (
	// FileName is the legacy YAML lockfile name. Retained for
	// transition-period reads until the cutover in Phase B.
	FileName = ".forge-lock.yaml"

	// HCLFileName is the canonical lockfile name from v0.5 onwards.
	HCLFileName = ".forge-lock.hcl"

	// header is prepended to written YAML lockfile content. The HCL
	// emitter has its own HCLHeader constant in emit_hcl.go.
	header = "# .forge-lock.yaml — DO NOT EDIT MANUALLY\n# Generated by forge. Changes will be overwritten on sync.\n"
)

// Lockfile tracks the provenance, variables, and sync state of a scaffolded project.
type Lockfile struct {
	Blueprint    BlueprintRef       `yaml:"blueprint"`
	CreatedAt    time.Time          `yaml:"created_at"`
	LastSynced   time.Time          `yaml:"last_synced"`
	ForgeVersion string             `yaml:"forge_version"`
	Variables    map[string]any     `yaml:"variables"`
	Defaults     []DefaultEntry     `yaml:"defaults,omitempty"`
	ManagedFiles []ManagedFileEntry `yaml:"managed_files,omitempty"`
}

// BlueprintRef identifies the source blueprint.
type BlueprintRef struct {
	RegistryURL string `yaml:"registry_url"`
	Name        string `yaml:"name"`
	Path        string `yaml:"path"`
	Ref         string `yaml:"ref,omitempty"`
	Commit      string `yaml:"commit,omitempty"`
}

// DefaultEntry tracks an inherited default file.
type DefaultEntry struct {
	Path         string `yaml:"path"`
	Source       string `yaml:"source"`
	Strategy     string `yaml:"strategy"`
	Hash         string `yaml:"hash,omitempty"`
	SyncedCommit string `yaml:"synced_commit,omitempty"`
}

// ManagedFileEntry tracks a file managed for ongoing sync.
type ManagedFileEntry struct {
	Path         string `yaml:"path"`
	Strategy     string `yaml:"strategy"`
	Hash         string `yaml:"hash,omitempty"`
	SyncedCommit string `yaml:"synced_commit,omitempty"`
}

// ContentHash computes the SHA256 hash of content in the format "sha256:<hex>".
func ContentHash(content []byte) string {
	h := sha256.Sum256(content)
	return "sha256:" + hex.EncodeToString(h[:])
}

// Write marshals the lockfile to YAML and writes it to the given path.
func Write(path string, lock *Lockfile) error {
	data, err := yaml.Marshal(lock)
	if err != nil {
		return fmt.Errorf("marshaling lockfile: %w", err)
	}

	content := []byte(header + string(data))

	if err := os.WriteFile(path, content, 0o644); err != nil {
		return fmt.Errorf("writing lockfile %s: %w", path, err)
	}

	return nil
}

// Read reads and parses a YAML lockfile from the given path.
//
// New callers should prefer LoadLockfile(dir), which dispatches
// between HCL (canonical) and YAML (transition-only) formats. Read
// stays available during the IMPL-0006 transition for callers that
// already have a YAML path and for the legacy YAML test fixtures.
// Phase B will retire it when the YAML loader is removed.
func Read(path string) (*Lockfile, error) {
	data, err := os.ReadFile(path) //nolint:gosec // lockfile path comes from known project directories
	if err != nil {
		return nil, fmt.Errorf("reading lockfile %s: %w", path, err)
	}

	var lock Lockfile
	if err := yaml.Unmarshal(data, &lock); err != nil {
		return nil, fmt.Errorf("parsing lockfile %s: %w", path, err)
	}

	return &lock, nil
}

// LoadLockfile reads the lockfile from dir. Only the canonical HCL
// form (.forge-lock.hcl) is supported from v0.5 onwards. A bare
// .forge-lock.yaml triggers a rescaffold-or-pin error per ADR-0002.
//
// IMPL-0007 will further refine the error wording when the migrate
// command is removed entirely.
func LoadLockfile(dir string) (*Lockfile, error) {
	hclPath := filepath.Join(dir, HCLFileName)

	if _, err := os.Stat(hclPath); err == nil {
		return LoadLockfileHCL(hclPath)
	} else if !errors.Is(err, os.ErrNotExist) {
		return nil, fmt.Errorf("stat %s: %w", hclPath, err)
	}

	yamlPath := filepath.Join(dir, FileName)
	if _, err := os.Stat(yamlPath); err == nil {
		return nil, fmt.Errorf(
			"lockfile %s: YAML lockfiles are no longer supported in this "+
				"version of forge; either rescaffold this project from the "+
				"current blueprint, or pin forge to v0.4.x (see "+
				"docs/MIGRATION.md)",
			yamlPath,
		)
	}

	return nil, fmt.Errorf("no lockfile found in %s (expected %s)", dir, HCLFileName)
}
