# .forge-lock.hcl — DO NOT EDIT MANUALLY
# Generated by forge. Changes will be overwritten on sync.

blueprint {
  registry_url = "github.com/donaldgifford/forge-registry"
  name         = "go-api"
  path         = "go/api"
  ref          = "main"
  commit       = "abc123def456"
}

created_at    = "2026-05-18T10:15:30.123456789Z"
last_synced   = "2026-05-19T08:00:00Z"
forge_version = "0.5.0"

variables {
  project_name        = "mockta"
  project_description = "A lightweight, embeddable Okta mock"
  use_docker          = true
  max_replicas        = 3
}

default "Makefile" {
  source        = "_defaults/Makefile.tmpl"
  strategy      = "overwrite"
  hash          = "sha256:cafe0001"
  synced_commit = "abc123def456"
}

default ".github/workflows/ci.yml" {
  source   = "_defaults/.github/workflows/ci.yml.tmpl"
  strategy = "merge"
}

managed_file "README.md" {
  strategy      = "overwrite"
  hash          = "sha256:cafe0002"
  synced_commit = "abc123def456"
}

managed_file "config.yaml" {
  strategy = "merge"
}
